# .travis.yml for `nihexporter`
# based on http://docs.travis-ci.com/user/languages/r/

dist: trusty
sudo: required
warnings_are_errors: false
language: r
cache: packages
r_build_args: '--no-build-vignettes'
r_check_args: '--as-cran --ignore-vignettes'
